### ISSUE TITLE
Consider other precommit approaches

### ISSUE THREAD

**Issue by pschanely** [pschanely/CrossHair#121]
Hello, I briefly looked over your repo and I'm unfamiliar with using a .py file for precommit... is there any reason you don't configure pre-commit with a `.pre-commit-config.yaml` and then run `pre-commit run all` or have a hook that runs pre-commit for you? A custom .py file feels like a lot of unnecessary customization at first glance... I'm not an expert here by the way, so if there's good reason I'm more than happy to be wrong. If though you'd like to transition to a pre-commit config I'd be more than happy to help close this issue with one. 
Cheers.

_Originally posted by @nicpayne713 in https://github.com/pschanely/CrossHair/issues/119#issuecomment-939202603_

**Comment by pschanely** [comment]
Greetings @nicpayne713! So precommit.py was also a contribution - it was a massive improvement over the prior setup which was, essentially, no precommit process at all. Note that we do have github actions set up to run this, so it is run automatically.

Personally, one thing I like about the plain python is that a potential contributor can understand and debug what's going on with just their existing knowledge of Python. Yes, it's more verbose than a yaml file, but it's also less magical; that's a tricky tradeoff to navigate.

So, I'm reluctant to introduce new tooling, at first glance. But perhaps [pre-commit](https://pre-commit.com/) gives us a bunch of other capabilities that swings the balance more clearly in its favor. Happy to be convinced.

**Comment by nicpayne713** [comment]
I just started using pre-commit earlier this year and after just a few minutes of looking over a stock config I think it is way easier to understand the your current .py file - mainly because there's existing documentation and the checks you may want to implement also already exist. pre-commit can also be configured to run easily locally as a git hook so that you prohibit yourself from even committing something that would break a build (within reason, it's not going to check build dependencies or anything to my knowledge). How about I toss something out there on a branch and let you tool around with it on your own before deciding to implement it?

**Comment by tekktrik** [comment]
Hey, I'm interested in picking this up (saw this as part of Hacktoberfest, digging the library!).  Mind if I take it?

**Comment by pschanely** [comment]
Please do! Thank you! There is a bunch of conversation in the #122 PR that's worth reviewing. Shoot fast and loose with questions, here or on [gitter](https://gitter.im/Cross_Hair/Lobby)!

**Comment by tekktrik** [comment]
Sounds great!  I'll get on this shortly.  I'll try to add as much from the previous conversation, but please let me know if I've missed anything or anything's changed when I submit!

**Comment by tekktrik** [comment]
Just wanted to say that I still intend to work on this, just have a few other things going on IRL.  Even if I can't get to it for Hacktoberfest, I still want to tackle this. :)
