### ISSUE TITLE
How do you analyze control flow?

### ISSUE THREAD

**Issue by saulshanabrook** [pschanely/CrossHair#23]
Hey!

This package is really impressive and I am just starting to look through it to better understand how it works. Thanks for putting it together!

One of my first questions was "how does it analyze python control flow?" Other libraries like this I have seen take one of a number of options:

1. Look at AST ([autograph](https://www.semanticscholar.org/paper/The-800-Pound-Python-in-the-Machine-Learning-Room-Decker-Moldovan/3f41ad1e7cf13fb1610b758464eac42cb30c69cc))
2. Look at bytecode ([numba](http://numba.pydata.org/))
3. "trace" function by passing in different values and looking at result ([jax](https://github.com/google/jax#compilation-with-jit))
4. Override cpython bytecode instructions ([codetransformers](https://github.com/llllllllll/codetransformer))

I tried looking a bit through the source code, but wasn't sure which approach you were using here. Just a pointer to a file would be helpful!

**Comment by pschanely** [comment]
Hi! Thanks for asking this question, and keep them coming! :)

I think CrossHair might be somewhat similar to option 3, but is at least a little different than all of those. CrossHair calls your function in a regular CPython interpreter, repeatedly, with "symbolic" arguments (which are also implemented as regular python objects). So, if your function takes an integer, we pass it [an object](https://github.com/pschanely/CrossHair/blob/e61f1adfb3c1bb21c4c932656e1d5ca2b3df0c93/crosshair/libimpl/builtinslib.py#L531) that acts like an integer. When an `if` statement happens, we [pick](https://github.com/pschanely/CrossHair/blob/e61f1adfb3c1bb21c4c932656e1d5ca2b3df0c93/crosshair/libimpl/builtinslib.py#L512) one path arbitrarily. Later, when we run the function again, we'll pick the other path. At the end of each path, we'll have either proven the postconditions true for that execution path, or found a counterexample.

Note this means that most functions will never be completely analyzed by CrossHair (if you have a loop, you likely have an infinite number of paths). But in practice, CrossHair is still pretty good at finding counterexamples.

[This description in The Fuzzing Book](https://www.fuzzingbook.org/html/SymbolicFuzzer.html#Symbolic-Fuzzing) will give you a much more complete idea of the approach.

Hope that helps!

**Comment by saulshanabrook** [comment]
Thanks @pschanely! Yes I agree it's similar to option 3... I am curious if you considered the other options when decided to implement this method. Do you think eventually you will have to model some subset of the Python interpreter and statically analyze the bytecode or AST?

I am curious because I have a project which is currently doing a simplified version of the tracing approach, but instead just restricting all control flow to functional ([fib to llvm example](https://github.com/Quansight-Labs/metadsl/blob/0bb4fe9d6979f55f817df8ef1a4b6ae479da330b/metadsl_llvm/ir_context_test.py#L20-L28)). Now I am considering changing it to support all of Python control flow and also to use Z3 to help with some substitutions.

Also just wanted to also say I am really impressed with this codebase so far... There is a lot to learn from here!

**Comment by saulshanabrook** [comment]
Ah one other thing, is it possible to get a look at the Z3 terms you create? Like for debugging purposes, to help me get my head around how some of this works.

**Comment by pschanely** [comment]
Yup! Advantages of this approach:
* You just use the regular Python interpreter - you don't need to model its behavior. Modeling the interpreter is **a lot** of work, and hard to get right.
* Because the analysis is per-path, you need essentially no quantifiers. Without a lot of care, quantified expressions will quickly sink Z3.

Disadvantages:
* Although you don't have to model the interpreter, you do have to model all the native data types. Easier, but still a lot of work, and still hard to get right.
* Unlike other approaches, you hit walls where you can't maintain the illusion. When under analysis, asking for `type(x)` likely doesn't tell you want you expect. We get around some of these cases with (extensive) monkey-patching, but these are typically delicate solutions.
* Incompleteness! (due to the path exploration limitations I mentioned earlier)

Right now, I am not seriously considering making the leap to interpreter-modeling - largely because there is still so much headroom for improving this "easy" approach. If I was going to attempt it, I think I'd probably attempt it at the bytecode level rather than the AST level; it feels like the opcode semantics are a little more rigorously specified.

As for dumping the z3 expressions in CrossHair, you can uncomment [this line](https://github.com/pschanely/CrossHair/blob/e61f1adfb3c1bb21c4c932656e1d5ca2b3df0c93/crosshair/statespace.py#L156) and run crosshair with the `-v` (verbose) option to see what z3 sees. Possibly we should add real verbosity levels to make this a regular feature.

If you decide to dig into Z3 (inside CrossHair, or for your project), you might find the [gitter chat](https://gitter.im/Cross_Hair/Lobby) an easy place to fire off quick questions. (and share your Z3 experiences back!)

**Comment by saulshanabrook** [comment]
> As for dumping the z3 expressions in CrossHair, you can uncomment this line and run crosshair with the -v (verbose) option to see what z3 sees. 

I tried that and run `crosshair check -v crosshair.examples.arith.double` but it doesn't log anything extra. Any ideas?

**Comment by pschanely** [comment]
For future readers of this bug (we resolved this over chat), the correct line to uncomment was actually here:

https://github.com/pschanely/CrossHair/blob/e61f1adfb3c1bb21c4c932656e1d5ca2b3df0c93/crosshair/statespace.py#L298
