### ISSUE TITLE
crosshair-tool installation in windows

### ISSUE THREAD

**Issue by roiDaniela** [pschanely/CrossHair#41]
when trying to pip install crosshair-tool on windows,
conda 4.9.2 ,python 3.7.4
I get the error:

ERROR: Command errored out with exit status 1: 'C:\Python\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\...\\AppData\\Local\\Temp\\pip-install-o1trm1ie\\z3-solver-crosshair\\setup.py'"'"'; __file__='"'"'C:\\Users\\....\\AppData\\Local\\Temp\\pip-install-o1trm1ie\\z3-solver-crosshair\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\...\AppData\Local\Temp\pip-record-yewf5w13\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by pschanely** [comment]
Thank you for this report. It's depressing to me to think how many people have probably tried this, failed, and not spoken up about it!
I've been meaning to get on an official z3 release for a while now, so I've just fast-tracked that work instead of debugging this directly. We are on the official 4.8.9.0 release of z3 as of [this commit](https://github.com/pschanely/CrossHair/commit/54c1d99925ba33b76401342af81fa049cd9516ed).
If you're willing to try a crosshair install from source (e.g. `python setup.py install`), I'd love to find out whether that works for you. Otherwise, I'll try to cut a crosshair-tool release on pypi soon and update this bug again then.

Thanks again for the report!

**Comment by roiDaniela** [comment]
pip install git+https://github.com/pschanely/CrossHair.git
worked

**Comment by pschanely** [comment]
I got one other report of the windows install now working, so I'm going to mark this one fixed; `crosshair-tool` will get this in PYPI as of version 0.0.9 which I'll release in the next week or so.

Thanks again, and I can't wait to hear more about what works for you and what doesn't!

**Comment by pschanely** [comment]
And just to close the loop: v0.0.9 is cut and on PYPI!
