### ISSUE TITLE
Make continuous integration/release run on GitHub

### ISSUE THREAD

**Issue by mristin** [pschanely/CrossHair#59]
Would you like me to translate the workflow from travis to GitHub?

Additionally, I can adapt a script such as [this one](https://github.com/mristin/icontract-hypothesis/blob/main/.github/workflows/publish-to-pypi.yml) for making releases to PyPI automatically whenever you release on GitHub.

It is probably easier to maintain the CI pipeline if everything runs on a single platform. Moreover, Travis seems to be in trouble (see, *e.g.*, [this thread on Hacker News](https://news.ycombinator.com/item?id=25338983)).

**Comment by pschanely** [comment]
I was aware that travis would stop working at some point and was just waiting until it actually broke. :)

I'm not very familiar with github actions, but if you think it'd work for us, let's do it!

Autopush to PyPI would be neat as well, though I don't cut releases all that often right now. Partly because my push to https://crosshair-web.org/ is a semi-manual process as well.
